---
- hosts: raspbian
  sudo: yes

  vars_files:
    - vars/main.yml

  tasks:
    - name: Update apt cache.
      apt:
        update_cache: yes
        cache_valid_time: 900

    - name: Install needed packages.
      apt:
        name: "{{ item }}"
        state: present
      with_items: install_packages

  handlers:
    - include: handlers/main.yml
